"""
Visualize the geometry generated by whistle_keychain.py
to understand the throat orientation
"""
import numpy as np
import matplotlib.pyplot as plt
from math import tau, cos, sin, radians, tan

# Design parameters (from whistle_keychain.py)
cylinder_diameter = 12
cylinder_radius = cylinder_diameter / 2
layer_height = 0.2
throat_section_start = 12  # mm from bottom
throat_depth = 8

# Throat geometry
throat_start_angle = radians(-15)
throat_end_angle = radians(15)
throat_angle = 75  # degrees from vertical

print("=== WHISTLE GEOMETRY ANALYSIS ===\n")

# Analyze at different Z heights in the throat section
print("THROAT SECTION (12-20mm Z):")
print(f"Throat opening: {throat_start_angle} to {throat_end_angle} radians")
print(f"  = {np.degrees(throat_start_angle):.1f}° to {np.degrees(throat_end_angle):.1f}°")
print(f"  = 30° arc centered on +X axis (angle=0°)\n")

# Show where the opening is in XY plane
print("Opening location in XY plane:")
print(f"  Start: X={cylinder_radius * cos(throat_start_angle):.2f}, Y={cylinder_radius * sin(throat_start_angle):.2f}")
print(f"  End:   X={cylinder_radius * cos(throat_end_angle):.2f}, Y={cylinder_radius * sin(throat_end_angle):.2f}")
print(f"  Center direction: +X axis")
print(f"  Opening arc: 30° slot\n")

# Analyze the ramp
print("RAMP GEOMETRY:")
throat_layers = int(throat_depth / layer_height)
for layer in [0, throat_layers//4, throat_layers//2, 3*throat_layers//4]:
    z = throat_section_start + layer * layer_height
    ramp_offset = layer * layer_height / tan(radians(throat_angle))
    current_ramp_radius = cylinder_radius - ramp_offset
    print(f"  Layer {layer:2d} (Z={z:.1f}mm): ramp_radius = {current_ramp_radius:.2f}mm (offset={ramp_offset:.2f}mm)")

print("\n=== ORIENTATION ANALYSIS ===")
print("Current design:")
print("  - Cylinder axis: VERTICAL (along Z)")
print("  - Throat opening: 30° slot on +X side of cylinder")
print("  - Ramp: moves radially inward (reduces radius)")
print("  - Air flow path: ??? (unclear how air enters and exits)")
print("\nOriginal STL:")
print("  - Main axis: HORIZONTAL (along X, 34.17mm)")
print("  - Cross-section: 5mm × 5mm square")
print("  - 75° angled surface: in X-Z plane")
print("  - Air flow: along X-axis, over angled ramp, hits labium edge")

print("\n=== THE PROBLEM ===")
print("The throat slot is perpendicular to the cylinder axis!")
print("For a whistle:")
print("  1. Air should flow ALONG the cylinder axis (Z direction)")
print("  2. Through a narrow windway channel")
print("  3. Exit and hit a labium edge perpendicular to flow")
print("\nBut current code:")
print("  1. Creates a side slot (perpendicular to Z axis)")
print("  2. No clear air inlet/outlet path along Z")
print("  3. Labium would be parallel to cylinder axis (wrong!)")

# Create a visualization
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

# Top view (XY plane) - show the throat opening
ax = axes[0, 0]
theta = np.linspace(0, tau, 100)
x = cylinder_radius * np.cos(theta)
y = cylinder_radius * np.sin(theta)
ax.plot(x, y, 'b-', linewidth=2, label='Cylinder outline')

# Show throat opening
throat_theta = np.linspace(throat_start_angle, throat_end_angle, 20)
throat_x = cylinder_radius * np.cos(throat_theta)
throat_y = cylinder_radius * np.sin(throat_theta)
ax.plot(throat_x, throat_y, 'r-', linewidth=4, label='Throat opening (30° arc)')

# Show center and axes
ax.plot(0, 0, 'ko', markersize=10)
ax.arrow(0, 0, cylinder_radius*1.3, 0, head_width=0.5, head_length=0.5, fc='green', ec='green')
ax.text(cylinder_radius*1.4, 0, '+X', fontsize=12, color='green')
ax.arrow(0, 0, 0, cylinder_radius*1.3, head_width=0.5, head_length=0.5, fc='purple', ec='purple')
ax.text(0, cylinder_radius*1.4, '+Y', fontsize=12, color='purple')

ax.set_xlim(-8, 10)
ax.set_ylim(-8, 10)
ax.set_aspect('equal')
ax.grid(True, alpha=0.3)
ax.legend()
ax.set_title('TOP VIEW (XY plane)\nZ-axis coming out of page\nThroat opens on +X side')
ax.set_xlabel('X (mm)')
ax.set_ylabel('Y (mm)')

# Side view (XZ plane) - show the ramp
ax = axes[0, 1]
z_layers = np.arange(0, throat_layers+1)
z_values = throat_section_start + z_layers * layer_height
ramp_offsets = z_layers * layer_height / tan(radians(throat_angle))
ramp_radii = cylinder_radius - ramp_offsets

# Show cylinder outline
ax.plot([throat_section_start, throat_section_start + throat_depth], [cylinder_radius, cylinder_radius], 'b-', linewidth=2)
ax.plot([throat_section_start, throat_section_start + throat_depth], [-cylinder_radius, -cylinder_radius], 'b-', linewidth=2)

# Show ramp (only on +X side where throat opens)
valid_layers = ramp_radii > 0
ax.plot(z_values[valid_layers], ramp_radii[valid_layers], 'r-', linewidth=3, label='Ramp surface')
ax.plot(z_values[valid_layers], -cylinder_radius*np.ones(sum(valid_layers)), 'b-', linewidth=2)

ax.set_xlabel('Z (mm) - vertical axis')
ax.set_ylabel('Radial distance from center (mm)')
ax.set_title('SIDE VIEW (looking along +Y axis)\nRamp moves radially inward')
ax.grid(True, alpha=0.3)
ax.legend()
ax.set_ylim(-8, 8)

# Cross-section at different Z heights
ax = axes[1, 0]
colors = ['blue', 'green', 'orange', 'red']
for i, layer in enumerate([0, throat_layers//3, 2*throat_layers//3, throat_layers-1]):
    z = throat_section_start + layer * layer_height
    ramp_offset = layer * layer_height / tan(radians(throat_angle))
    current_ramp_radius = cylinder_radius - ramp_offset

    if current_ramp_radius > 0:
        # Full circle except throat arc
        theta_full = np.linspace(throat_end_angle, throat_end_angle + tau - (throat_end_angle - throat_start_angle), 100)
        x_full = cylinder_radius * np.cos(theta_full)
        y_full = cylinder_radius * np.sin(theta_full)
        ax.plot(x_full, y_full, color=colors[i], linewidth=2, label=f'Z={z:.1f}mm')

        # Ramp arc (different radius)
        theta_ramp = np.linspace(throat_start_angle, throat_end_angle, 20)
        x_ramp = current_ramp_radius * np.cos(theta_ramp)
        y_ramp = current_ramp_radius * np.sin(theta_ramp)
        ax.plot(x_ramp, y_ramp, color=colors[i], linewidth=3, linestyle='--')

ax.set_xlim(-8, 8)
ax.set_ylim(-8, 8)
ax.set_aspect('equal')
ax.grid(True, alpha=0.3)
ax.legend()
ax.set_title('CROSS-SECTIONS at different Z heights\nShowing ramp moving inward on +X side')
ax.set_xlabel('X (mm)')
ax.set_ylabel('Y (mm)')

# Text summary
ax = axes[1, 1]
ax.axis('off')
summary_text = """
PROBLEM DIAGNOSIS:

CURRENT GEOMETRY (WRONG):
• Vertical cylinder (Z-up)
• Throat: 30° slot on +X side
• Ramp: radially inward taper
• Air path: UNCLEAR!

WHERE TO BLOW?
• No mouthpiece at top/bottom
• Side slot doesn't create channel
• No labium edge for air to hit

CORRECT WHISTLE GEOMETRY:
• Mouthpiece: at one END
• Windway: narrow channel along
  cylinder axis
• Labium: sharp edge perpendicular
  to air flow
• Chamber: beyond labium for resonance

THE FIX NEEDED:
1. Reorient: throat should run along
   Z-axis (cylinder axis)
2. Mouthpiece: top end (Z=0)
3. Windway: narrow vertical channel
4. Labium: horizontal edge at ~Z=12mm
5. Air flows DOWN through channel,
   hits labium edge, enters chamber
"""
ax.text(0.1, 0.9, summary_text, transform=ax.transAxes,
        fontsize=11, verticalalignment='top', fontfamily='monospace',
        bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

plt.tight_layout()
plt.savefig('whistle_geometry_analysis.png', dpi=150, bbox_inches='tight')
print("\n✓ Saved visualization to whistle_geometry_analysis.png")
print("\nThe throat is oriented 90° wrong!")
print("It's a SIDE SLOT when it should be an AXIAL CHANNEL")
